<!-- Slider main container -->
<div class="swiper">
    <div class="swiper-wrapper">
        <!-- Slides -->
        <div class="swiper-slide">
            slide 1
        </div>
        <div class="swiper-slide">
            slide 2
        </div>
        <div class="swiper-slide">
            slide 3
        </div>
    </div>
    <!-- Pagination --> 
    <div class="swiper-pagination"></div>
    
    <!-- Navigation buttons --> 
    <div class="swiper-button-prev"></div>
    <div class="swiper-button-next"></div>

    <!-- If we need scrollbar --> 
    <div class="swiper-scrollbar"></div>
</div>

<script type="text/x-magento-init">
     {
         "*": {
             "customCarrousel": {}
         }
     }
 </script>